- .travis.yml
- CHANGELOG.md
- bin/codeclimate
- composer.json
**READY**
Held for https://github.com/honeybadger-io/honeybadger-php/pull/65
Update the Travis configuration so there is better coverage across Laravel versions. This is expected to fail for Laravel 5.5 versions until the related PR on `honeybadger-php` is tagged and released.
List related PRs against other branches:
* https://github.com/honeybadger-io/honeybadger-php/pull/65
- n/a Tests
- n/a Documentation
Review CI Process
> Update Travis and honeybadger-php version

- .travis.yml
- CHANGELOG.md
- composer.json
**READY**
Held for #14.
Adds support for Laravel 5.7
n/a
- n/a Documentation
```bash
```
> Adds support for Laravel 5.7

- .travis.yml
- CHANGELOG.md
- composer.json
**READY**
Adds PHP 7.3 to the Travis build matrix and removes unnecessary over specification of php versions in the composer manifest.
List related PRs against other branches:
* https://github.com/honeybadger-io/honeybadger-php/pull/68
Watch CI process of PR
> Add php73 support

- src/Commands/HoneybadgerDeployCommand.php
- src/HoneybadgerServiceProvider.php
- src/Middleware/UserContext.php
- tests/Commands/HoneybadgetDeployCommandTest.php
**WIP**
Adds a deploy command `honeybadger:deploy`. Unless the options are passed to the command it will resolve params from the Laravel/Honeybadger config ([config/honeybadger.php](https://github.com/honeybadger-io/honeybadger-laravel/blob/master/config/honeybadger.php)) and system calls to get the git hash and local username. The command will merge options together if mixed options are passed.
**Options:**
`honeybadger:deploy --apiKey="" --environment="" --revision="" --repository= --username=""`
Resolves #25
***I STILL NEED TO DO FINAL TESTING TO HONEYADGER IN PRODUCTION***
n/a
```bash
```
> Add deploy command

- CHANGELOG.md
- src/Middleware/HoneybadgerContext.php
- src/Middleware/UserContext.php
Adds a new middleware which should be referenced in the documentation `HoneybadgerContext`. I updated the current `UserContext` middleware to extend this prevent a breaking change. This will set and send the controller and action if available.
**DEPENDS ON**: https://github.com/honeybadger-io/honeybadger-php/pull/87
```bash
```
> Adds controller and action to the context

- CHANGELOG.md
- src/Middleware/HoneybadgerContext.php
- tests/Fixtures/TestController.php
- tests/UserContextMiddlewareTest.php
Fixes an issue introduced with 1.7.0 with request component and action. This ensures that they are present before attempting to set them. Defaults to string if it slips through per the contract.
Resolves https://github.com/honeybadger-io/honeybadger-laravel/issues/34
```bash
```
> Add a check to ensure component and action are set

- CHANGELOG.md
- src/HoneybadgerLaravel.php
- src/Middleware/HoneybadgerContext.php
- tests/Fixtures/TestInvokableController.php
- tests/UserContextMiddlewareTest.php
We needed to split up the checks for the component and the action. Laravel will set the component to 'Closure' for closure routes and will send the controller name for invokables.
Resolves #36 
```bash
```
> Fix component without action

- .travis.yml
- CHANGELOG.md
- composer.json
Laravel 6 has a minimum version for Monolog which is incompatible with
honeybadger-io/honeybadger-php. This library will need to utilize
honeybadger-php:^2.0 to allow support for Laravel 6.
List related PRs against other branches:
- https://github.com/honeybadger-io/honeybadger-php/pull/91
```bash
```
> Remove Laravel 6 Support

- .travis.yml
- composer.json
Version 2 base changes
- Update dependency minimum version
- Laravel/Illuminate
- Honeybadger PHP
- Removed support for PHP 7.1
- Removed support for Laravel/Illuminate 5.x
- Update Travis config to reflect new support
- https://github.com/honeybadger-io/honeybadger-laravel/pull/40
- https://github.com/honeybadger-io/honeybadger-php/pull/91
```bash
```
1.
> Version two base changes

- .php_cs
- CHANGELOG.md
- src/HoneybadgerServiceProvider.php
Adds a new method for scheduled tasks to only ping Honeybadger's check-in when the task was successful. The current implementation (`thenPingHoneybadger()`) runs regardless of success or failure.
```php
protected function schedule(Schedule $schedule)
{
$schedule->command('inspire')
->hourly()
->pingHoneybadgerOnSuccess('123456');
}
```
Closes #47
> Add pingHoneybadgerOnSuccess to scheduled tasks

- src/HoneybadgerLaravel.php
**READY**
When the SDK can't send data to the backend (e.g. invalid API key, SSL verification failed, network problems), a `ServiceException` is thrown This PR will log the service exception rather than letting it crash the app and [hide the original exception](https://github.com/honeybadger-io/honeybadger-php/pull/129)..
Fixes https://github.com/honeybadger-io/honeybadger-php/pull/129.
PHP: https://github.com/honeybadger-io/honeybadger-php/pull/129
- Add a route that throws an exception:
```php
Route::get('/', function () {
throw new \Exception("Oh fuck no!");
});
```
- Set an invalid API key in your .env: `HONEYBADGER_API_KEY=dfdfdwrerrrrrrrrrr`
- Start the app: `php artisan serve`
- Visit the app on http://127.0.0.1:8000. The service exception should be logged in …
> Don't crash on service exception

- .gitignore
- phpunit.xml.dist
- src/CommandTasks.php
- src/Commands/HoneybadgerInstallCommand.php
- src/Commands/HoneybadgerTestCommand.php
- src/HoneybadgerServiceProvider.php
- src/Installer.php
- tests/Commands/HoneybadgerInstallCommandTest.php
- tests/Commands/HoneybadgerTestCommandTest.php
- tests/Commands/HoneybadgetDeployCommandTest.php
- tests/Commands/InstallerTest.php
**READY**
Follow up to #70. The Honeybadger client shouldn't throw errors, but in certain cases (the `test` and `install` commands, we definitely want it to throw an error if there was a problem.
This PR achieves that by adding a separate `honeybadger.loud` binding to the DI container — another client instance, but one that will fail loudly (crash on errors).
(I had to refactor a few things internally to get it to work properly, but the behaviour of the command is the same.)
> Update install and test commands to fail loudly

- tests/Commands/HoneybadgetDeployCommandTest.php
READY
Adds compatibility with PHPUnit 10
When running the tests PHPUnit gave this warning `assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.`
This PR does the recommended change, while still keeping compatibility with PHPUnit 8.
> prepare for phpunit 10

- .gitattributes
READY
.styleci.yml should not be needed in the export, unless i'm totally mistaken (not a styleci user), but laravel/framework as an example does not export it.
> ignore styleci config from export

- src/HoneybadgerServiceProvider.php
- tests/HoneybadgerEventPingTest.php
READY
Adds a second argument to the `thenPingHoneybadger` and `pingHoneybadgerOnSuccess` methods that allows you to specify one or more environments when to checkin, it can be omitted to always checkin (current behaviour).
The PR includes tests.
I also added a `string` typehint for the $id argument, which should be 100% backwards compatible since the Reporter checkin method already does the same typehint.
```php
$schedule->command(SendEmails::class)
->daily()
->thenPingHoneybadger('Jiy63Xw', 'production'); // will only checkin on production
```
```php
$schedule->command(SendEmails::class)
->daily()
->thenPingHoneybadger('Jiy63Xw', ['production', 'development']); // will only checkin on production and development
```
> add $environments arguments to ping methods

- src/HoneybadgerLaravel.php
**READY**
Follow-up to a discussion on Slack with @stympy. This PR includes the base PHP SDK's version in reports (helpful for debugging purposes).
Question: is the current `version` field used anywhere on the backend (example, comparing if `notifier.version == '3.5.0'`)? If it is, then this PR might break some behaviour; if not, we're good.
> Include PHP SDK version in reports

- src/Breadcrumbs/Breadcrumb.php
**READY**
Fixes #80.
Since the breadcrumbs collection runs synchronously in the same process as the user's app (and on every request), it will crash their app if something goes wrong. This is obviously not desirable, so it's better to just silence errors instead.
> Silence any errors from breadcrumbs

- CHANGELOG.md
- composer.json
- src/ContextManager.php
- src/HoneybadgerLaravel.php
- src/Middleware/HoneybadgerContext.php
- src/Middleware/UserContext.php
- tests/Fixtures/TestController.php
- tests/ReporterTest.php
**READY**
This PR removes the need for adding the `HoneybadgerContext` middleware. Instead, when reporting an error, the client will retrieve the context itself (user context and route action) and send. This is better because:
- No need setting context on each request; only set when we actually encounter an error
- Simpler setup
- Docs PR (TODO)
Create a Laravel app set up with Honeybadger and user auth. Remove the `HoneybadgerContext` middleware. Get the app to throw an error. The user ID and route action info should be present in your dashboard.
> Automatically add user and route context

- .styleci.yml
- CHANGELOG.md
- config/honeybadger.php
- src/HoneybadgerLaravel.php
**READY**
Closes #83
Sets `report_data` to default to excluding local and test environment. Decided against adding a separate "development environments" config, because the precedence can be confusing—does `report_data: true` mean "report data even if in these environments", or "report data only if *not* in these environments"? It's simpler to have one configuration to control reporting of data,
> Add report_data to config

- CHANGELOG.md
- src/Commands/HoneybadgerInstallCommand.php
Fixes #88 by writing `HONEYBADGER_VERIFY_SSL=true` to `.env` as well.
> Set SSL default in .env during install (fix #88)

- composer.json
**READY**
`sixlive/dotenv-editor=^2.0` drops support for PHP 7, which `thenpingme/laravel=^3.0` uses. As a result, this package and `thenpingme/laravel` cannot currently be installed alongside each other.
No related PRs or branches.
- [NA] Tests
- [NA] Documentation
```bash
composer create-project laravel/laravel hblaravel
cd hblaravel
composer require honeybadger-io/honeybadger-laravel
composer require thenpingme/laravel=^3.0
```
> Add support for PHP ^8.0 exclusively

- CHANGELOG.md
- composer.json
- src/Commands/HoneybadgerCheckInCommand.php
- src/Commands/HoneybadgerCheckInsSyncCommand.php
- src/HoneybadgerLaravel.php
- src/HoneybadgerServiceProvider.php
- tests/Commands/HoneybadgerCheckInCommandTest.php
- tests/Commands/HoneybadgerCheckInsSyncCommandTest.php
**READY**
To keep the language consistent, this PR renames all references of checkins to check-ins or checkIns (depending on the context).
**Note**: To maintain backwards compatibility, I kept the `checkin` commands as they are.
> refactor(check-ins): checkins to check-ins

- composer.json
- config/honeybadger.php
- src/Commands/HoneybadgerDeployCommand.php
- src/Commands/HoneybadgerInstallCommand.php
- src/Commands/HoneybadgerTestCommand.php
- tests/Commands/HoneybadgerInstallCommandTest.php
**READY**
- Adds configurable endpoints in config file.
- Adds optional parameters to _install_ command for endpoint and app endpoint.
The install command for HB EU becomes:
```
php artisan honeybadger:install API_KEY --endpoint https://eu-api.honeybadger.io --appEndpoint https://eu-app.honeybadger.io
```
Closes #137.
> feat: add support for eu endpoints with install command

- config/honeybadger.php
- src/Events/ApplicationEvent.php
- src/Events/MessageLogged.php
- src/HoneybadgerLaravel.php
- src/HoneybadgerServiceProvider.php
**READY**
The `MessageLogged` event was raised by Laravel and we were using it to send logs as events to Insights.
If there was an exception while sending the event to insights, we would do a Log::warning which would trigger the `MessageLogged` event and try to send an event to Insight again, causing an infinite loop. Note that the infinite loop wouldn't necessarily crash the app because the events are sent in batches (see `BulkEventDispatcher`), but the amount of logs would grow a lot.
We also have another way to send logs as events Honeybadger Insights (manually configured), the `HoneybadgerLogEventDriver` which can be added as a separate log channel. This is a monolog handler which comes with built-in support for log levels and infinite loop protection. Hence, if you would end up in a …
> fix: stop using the MessageLogged event for events api

- .github/workflows/run-tests.yml
- src/HoneybadgerLaravel.php
- src/Installer.php
Same as with Honeybadger PHP library. Removed the deprecation warnings. There a lot of tests skipping. I'm not sure, if that was the default behaviour before 8.4.
> perf: add PHP 8.4 to test matrix

- src/HoneybadgerLaravel.php
**READY**
Fixes #153.
- Get a `request` instance variable using the facade instead of the `request()` helper function.
- Additionally, adds a call to `HoneybadgerLaravel::shouldReport` before calling `Honeybadger::notify` (note: `Honeybadger::notify` calls `Honeybadger::shouldReport` as well).
> fix: get request instance using facade

- composer.json
- config/honeybadger.php
- src/Facades/Honeybadger.php
- src/HoneybadgerServiceProvider.php
- src/Middleware/FlushEvents.php
- tests/HoneybadgerServiceProviderTest.php
**READY**
Adds a terminable middleware for flushing the events queue after the response is sent.
> feat: flushEvents with terminable middleware
