honeybadger-io/honeybadger-laravel

CHANGELOG.md
src/Commands/HoneybadgerTestCommand.php
src/Exceptions/TestException.php
tests/Commands/HoneybadgerTestCommandTest.php

**READY**
Adds a package specific test exception for clarity in the Honeybadger application.
- ~~[ ] Documentation~~ Not Needed

Add specific test exception

---

CHANGELOG.md
README.md
src/HoneybadgerServiceProvider.php
tests/HoneybadgerEventPingTest.php

**READY**
* Adds scheduled command macro to ping Honeybadger after the command has ran.
* Some cleanup around the documentation
```bash
> git checkout add-scheduled-event-helper
```

Add scheduled event helper

---

.scrutinizer.yml

**READY**
There are duplicated rules across StyleCI and Scrutinizer as well as false positives.
- ~~[ ] Tests~~ n/a
- ~~[ ] Documentation~~ n/a
- ~~[ ] Changelog Entry (unreleased)~~ n/a
Review scrutinizer report on this PR

Cleanup Scrutinizer CI

---

composer.json

**READY**
There is no reason to specify the upper limit to these packages. 
n/a
Review Travis output in cross version testing

Update package version constraints

---

.travis.yml

Update CI for Laravel 5.8

---

.travis.yml
composer.json

**WIP**
Add support for the newly released Laravel 6

Add Laravel 6 support

---

CHANGELOG.md
composer.json

Increase the minimum version of the [honeybadger-php](https://github.com/honeybadger-io/honeyabdger-laravel) package

Increase minimum version of the honeybadger-php package

---

CHANGELOG.md
phpunit.xml.dist
src/Middleware/HoneybadgerContext.php
tests/TestCase.php

Fixes route action and component for Lumen.
**Needs to be back ported to 1.x with a patch as well as 6.0.x**
Resolves https://github.com/honeybadger-io/honeybadger-laravel/issues/39
```bash
```

Fix route action for lumen

---

.github/workflows/run-tests.yml
.travis.yml
CHANGELOG.md
composer.json
phpunit.xml.dist

- Adds support for Laravel 8
- Drops PHPUnit pretty print formatter
Closes #57 
Closes #58

Adds support for Laravel 8

---

src/CommandTasks.php
src/Commands/HoneybadgerInstallCommand.php
tests/CommandTasksTest.php
tests/Commands/HoneybadgerInstallCommandTest.php

Allow install failures except sending the test to Honeybadger.

Allow some install failures

---

config/honeybadger.php
src/Commands/HoneybadgerInstallCommand.php
tests/Commands/HoneybadgerInstallCommandTest.php
tests/Commands/HoneybadgetDeployCommandTest.php

Adds the verify config [honeybadger-php#123](https://github.com/honeybadger-io/honeybadger-php/pull/123) and [honeybadger-php#124](https://github.com/honeybadger-io/honeybadger-php/pull/124)

Add SSL verification config

---

config/honeybadger.php

**READY**
See https://github.com/honeybadger-io/honeybadger-laravel/issues/67#issuecomment-779149634. This adds helpful short descriptions of each option, as is the Laravel convention.
One consideration I had while doing this: Should the default timeout for the client be 0? This will cause requests to wait infinitely, and can lead to some unexpected scenarios, as well as crash a user's app if Honeybadger is unreachable. I'm thinking we want to use a sensible default, like 10s(?).

Added descriptive comments to config file

---

src/Commands/HoneybadgerInstallCommand.php
src/Commands/HoneybadgerTestCommand.php
src/HoneybadgerLaravel.php
tests/Commands/HoneybadgerTestCommandTest.php

Warn of `report_data` when running a test

---

config/honeybadger.php

See https://github.com/honeybadger-io/honeybadger-php/pull/151

Set default client timeout

---

CHANGELOG.md
config/honeybadger.php
src/HoneybadgerLaravel.php

Small fix needed for https://github.com/honeybadger-io/honeybadger-php/pull/160 to work

Call shouldReport() of parent

---

CHANGELOG.md
src/HoneybadgerLaravel.php
src/HoneybadgerServiceProvider.php

Closes https://github.com/honeybadger-io/honeybadger-laravel/issues/99

Correct feedback form URL

---

CHANGELOG.md
src/HoneybadgerLaravel.php
src/HoneybadgerLogDriver.php
tests/Commands/HoneybadgerCheckinCommandTest.php
tests/Commands/HoneybadgerInstallCommandTest.php
tests/Commands/HoneybadgerTestCommandTest.php

Other part of a fix for #105 / logger improvements
Related:
- https://github.com/honeybadger-io/docs/pull/326
- https://github.com/honeybadger-io/honeybadger-php/pull/168

Logger fixes

---

CHANGELOG.md
composer.json

**READY**
Update `honeybadger-php` dependency to latest version.

Update to latest honeybadger-php

---

CHANGELOG.md
src/Commands/HoneybadgerCheckinCommand.php
src/HoneybadgerServiceProvider.php

**READY**
Changes parameter names to be more descriptive, since now we accept a checkin id or name.
- https://github.com/honeybadger-io/honeybadger-php/pull/176

feat: checkin using name

---

CHANGELOG.md
composer.json
src/Commands/HoneybadgerCheckInCommand.php
src/HoneybadgerLaravel.php
tests/Commands/HoneybadgerCheckInsSyncCommandTest.php

**READY**
See https://github.com/honeybadger-io/honeybadger-php/pull/189

feat: conform to latest check-ins configuration api

---

.github/workflows/run-tests.yml
CHANGELOG.md
composer.json
config/honeybadger.php
phpunit.xml.dist
src/Breadcrumbs/MailBreadcrumb.php
src/Commands/HoneybadgerDeployCommand.php
src/HoneybadgerLaravel.php
src/HoneybadgerLogDriver.php
tests/AutomaticBreadcrumbsTest.php
tests/CommandTasksTest.php
tests/Commands/HoneybadgerCheckInCommandTest.php
tests/Commands/HoneybadgerInstallCommandTest.php
tests/Commands/HoneybadgerTestCommandTest.php
tests/LogDriverTest.php

Add support for Laravel 11 and remove support for Laravel < 10.
Closes #119

chore!: support Laravel 11

---

.github/workflows/check-pr-title.yml
.github/workflows/release.yml

ci: add release automation

---

.github/workflows/check-pr-title.yml

**READY**
Stores the PR title in an environment variable before usage. This should prevent any unwanted remote code execution.

ci: store pr title before usage

---

.github/workflows/release.yml
README.md
scripts/SyncSourceCodeWithPackageVersion.php

**READY**
Adds a script to update `HoneybadgerLaravel.php` when a release is created with Release Please. With this, we will have the release process fully automated :)

ci: script to auto update HoneybadgerLaravel.php version

---

src/ContextManager.php

…AuthIdentifier()" exception stopping the actual exception from getting reported
**READY/WIP/HOLD**
A few sentences describing the overall goals of the pull request's commits.
List related PRs against other branches:
branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()
```bash
```
1.

fix: check for getAuthIdentifier before calling it

---

.github/workflows/release.yml
composer.json
tests/LogEventDriverTest.php

**READY**
Updates to latest version of honeybadger-php.

chore: update honeybadger-php package

---

config/honeybadger.php

See https://github.com/honeybadger-io/honeybadger-php/pull/227

feat: add Insights event sampling
